### ISSUE TITLE
HUD planned for Sauerland map?

### ISSUE THREAD

**Issue by RamonaTigier** [EpochSC/SingleCurrencyBanking#4]
As Sauerland community is growing - and besides my private server using ;o) - is there a plan to release/build one Sauerland folder? 
Or can you just help and explain? 
Saw your screeny on opendayz, but couldn't reach as you PM is full or offline due to many questions like these. ;o(
sorry for disturbing. 
will try to do on my own, but I'm new to Epoch/DayZ and would love to have some more infos how to implement. 
many thanks
'Mona

**Comment by Windmolders** [comment]
Hi Mona,

Opendayz? do i have any posts on there related to this?

The HUD can be easely copied to your server. It doesnt require any map related stuff.

Just copy the addons folder from the github. 

And include it in your init.sqf on the bottom like this:

if (!isDedicated) then {
if (DZE_AsReMix_PLAYER_HUD) then {
    execVM "addons\playerhud\playerHud.sqf"//AsReMix Player HUD
};
};

For further assistence, add my on skype: Xertie

**Comment by RamonaTigier** [comment]
Hi, 

sounds easy. 
"DZE_AsReMix_PLAYER_HUD = true; //Open Custom AsReMix Player HUD" 
is needed too in init.sqf? (just had a look into code while "waiting"... xD )

and opendayz... no.. _blush_
it is http://epochmod.com/forum/index.php?/topic/14414-release-how-to-make-custom-player-hud-by-asremix/page-3
sorry for confusion. looking for nice features for my server and found that 2 sides are best (atm). :) 

dont use skype, as it is not allowed here.. 

by the way, would you mind asking how to add easily new vehicles?? 
http://bwmod.armedassault.info/downloads.php
Fuchs and Fennek would be nice on my Sauerland, but not sure if they fit and work as is... :/ 

Many thanks for comeback..

'Mona

**Comment by Windmolders** [comment]
Well ya, you need that, if it still uses that.

And the new vehicles require you to add pbo's to your server, ALL PLAYERS ALSO NEED TO PLACE THESE IN THEIR PBO's. So i recommend not doing it :). You will not be be a default mod like epoch server anymore.

BTW my debug has the coins for single currency in it etc, you might want to slightly edit yours.

**Comment by RamonaTigier** [comment]
yeah.. single currency is one of the points that brought me to your git.. :)
hopefully implementing this weekend.. as my players dont like too much briefcases, gold, silver, bronce and aluminium in their backpacks.. ^^
by the way, good hint with pbos.. maybe i will try with pbos or not.. we will see..

many thanks for your help so far.. _like_ :+1:

**Comment by RamonaTigier** [comment]
ok, tried, but get following error:
"Warning Message: Resource title AsReMixhud not found
Error in expression <ace getVariable "AsReMixhud";
_vitals = _wpui displayCtrl 4900;

_thePlayer = pl>
  Error position: <_wpui displayCtrl 4900;

_thePlayer = pl>
  Error Undefined variable in expression: _wpui
File mpmissions__CUR_MP.sauerland\addons\playerhud\playerHud.sqf, line 12
Warning Message: Resource title AsReMixhud not found
Error in expression <ace getVariable "AsReMixhud";
_vitals = _wpui displayCtrl 4900;"

in playerHud.sqf there is:
"11     _wpui = uiNameSpace getVariable "AsReMixhud";
12    _vitals = _wpui displayCtrl 4900;"

something wrong in line 11? or did I miss something?

many thanks, if you like to help. :)

**Comment by Windmolders** [comment]
Sorry you also need this in your description.et

class RscTitles
{
#include "addons\playerhud\hud.hpp"
};

**Comment by RamonaTigier** [comment]
nearly.. :) 
had to add:

"//Open Custom AsReMix Player HUD start
#include "addons\playerhud\commonhud.hpp"
#include "hw.hpp"

class RscTitles
{
#include "addons\playerhud\hud.hpp"
};
//Open Custom AsReMix Player HUD end"

but now works. :) 

Thanks again!! :)

**Comment by Windmolders** [comment]
Done
